export const String = {
  visio: 'Vision : ',
  tovision: 'To Provide Single Platform',
  Mission: 'Mission : ',
  Tomission: 'To enlist Consultants',
  con: 'Contractors, Promoters, Material/',
  equ: 'Equipment- Suppliers/Stores',
  man: 'Manpower Suppliers and Funding',
  agen: 'Agencies in Mobile App.',
  forall: 'for all Stakeholders of Construction',
  pro: 'Projects in India.',
  welcom: 'Welcome to \nWebuildindia App',
  forgotpass: 'Forgot Password?',
  login: 'Login',
  registertoget: 'Hello! Register to \nget started',
  regis: 'Register',
  did: "Didn't recieve OTP? ",
  resend: 'Resend OTP',
  register: 'Registered!',
  youhave: 'You have been registered\n successfully.',
  getstarted: 'Get Started',
  gorgotpass: 'Forgot \nPassword?',
  dontworry: "Don't worry! Please enter the email\naddress linked with your account.",
  sendcode: 'Send Code',
  create: 'Create New\nPassword',
  yournewpasswor: 'Youe new password must be unique from\nthose previously used.',
  resendpassword: 'Resend Password',
  change: 'Password Changed!',
  successfully: 'Your password has been changed\n successfully.',
  backto: 'Back to Login',
  buss: 'Builder',
  agree: 'Agencies',
  treading: 'Trending News',
  Architects: 'Architects',
  Structurai: ' Structural Designers',
  soil: 'Soil investigation',
  Land: 'Land Surveyor',
  a: 'A',
  sd: 'SD',
  si: 'SI',
  ls: 'LS',
  viewde: 'View Details',
  ssnc: 'SSNC',
  arch: 'Arch Works',
  near: 'Near DPS School, Main Street, Kk Nager Chennal, Tamil, Nadu,',
  morevieww: 'View More ',
  t: 'T',
  company: 'Company Description',
  loremipum: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",
  contactdeta: 'Contact Details',
  mrname: 'Mr.Name Surname',
  simply: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  contacts: 'Contacts',
  location: 'Location',
  azx: 'balakrishna nagar, west mambalam, chennai-33, tamilnadu',
  deshbo: 'Dashborard',
  live: 'Live Ads',
  payment: 'Payment',
  Expried: 'Expired Ads',
  ssncarch: 'SSNC Arch Works',
  creaddd: "Create Ads",
  expri: 'Expried Ads',
  review: 'Renew',
  youcan: 'You can create 2 more ads \n on your subscription',
  next: 'Next',
  sub: 'Subscription Plan',
  basic: 'Basic',
  subscri: 'Subscribe',
  advan: 'Advanced',
  preminu: 'Premium',
  purchase: 'Purchase',
  subsce:'Subscribe',
  platinum: 'Platinum',
  createyour: 'Create Your Ads',
  Compname: 'Company Name',
  CompanyDescri: 'Company Description',
  addre: 'Company Address',
  catagories: 'Categories',
  subcat: 'Sub-Categories',
  phone: 'Phone Number',
  email: 'E-Mail Id',
  pin: 'PIN Code',
  city: 'City',
  State: 'State',
  addimg: 'ADD Your Image',
  Uploimg: 'Upload 4 Photo Of Your\n Company Image',
  or: 'Or',
  OpenCa: 'Open Camera To Take Images',
  save: 'Save',
  setectedfile:'Select file',
  view:'View',
  messagess:'Message',
  calls:'Calls',
   this:'This month',
   lastes:'Lastest',
   yourpro:'Your Profile',
   pareson:'Company Person',
   login:'Login', 
   Conform:'Confirm',
   cyb:'Create Your Business',
   clirntpro:'Client Profile',
   companies:'Companies',
   asb:'ASB (P) LTD',
   ltd:"Lorem Ipsum is Simply Dummy Text of The Printing and Typesetting Industry. Lorem Ipsum Has Been The Industry's Standard Dummy Text Ever Since The 1500s, When An Unknown Printer Took A Galley Of Type And Scrambled",
  agency:'Agency Performance',
  subsc:'Subscription',
  free:'Fees', 
  price:'Price',
  planname:'Plan name',
  addclient:'Add Client',
  addres:'Address',
  area:'Area',
  Uploimgs: 'Upload 5 Photo Of Your\n Company Image',
already:'Already have an account ?  ',
loginnow:'SignUp Now',
loginrsc:'Login Now',
logoutaccout:'LogOut',
updateprofle:"Upload Your Profile",
addcom:'Add company',
ASB:'ASB (P) LTD',
Amrithaa:'Amrithaa (P) LTD',
Neydu:'Neydu (P) LTD',
createadd:'Create Ads',
CreatecompanyDetails:'Create  Company Details',
AlternativeNumber:"Alternative Number", 
personName:'Person Name',
ConstructionBusiness:" My Construction Business"
}